---
title: "Linear model"
output: html_document
date: "2024-03-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Effect size by genotype plots, omega-3 %
```{r}

calculate_ci_lower <- function(point_estimate, standard_error) {
  z_value <- qnorm(0.975)  
  
  lower_bound <- point_estimate - z_value * standard_error
  
  return(lower_bound)
}

calculate_ci_upper <- function(point_estimate, standard_error) {
  z_value <- qnorm(0.975) 
  
  upper_bound <- point_estimate + z_value * standard_error
  
  return(upper_bound)
}

pheno <- as_tibble(import("/path/to/file/containing/phenotype/data"))
pheno <- pheno %>% select(c('IID', 'Status', 'w3FA_TFAP_resinv', 'age', 'sex', 'age_by_sex', paste0('PCA', 1:10)))

geno <- as_tibble(read_delim("/path/to/file/containing/all/particpants/genotype/data/for/the/top/SNP"))

geno$rs35473591_CT <- round(geno$rs35473591_CT, digits = 0)

geno <- dplyr::select(geno, c('IID', 'rs35473591_CT'))

pheno <- left_join(pheno, geno, by = 'IID', keep=F)

pheno <- dplyr::select(pheno,-IID)


CC_group <- pheno %>% dplyr::filter(rs35473591_CT == 2) 
CTCT_group <- pheno %>% dplyr::filter(rs35473591_CT == 0) 
C_CT_group <- pheno %>% dplyr::filter(rs35473591_CT == 1) 

predictors <- c('age', 'age_by_sex', 'sex', paste('PCA', 1:10, sep=""), 'Status')

subgroups <- list(CC_group, CTCT_group, C_CT_group)
final_df <- data.frame(matrix(nrow = 0, ncol = 3))
names(final_df) <- c('Beta', 'SE', 'rs35473591_CT')

for (i in seq_along(subgroups)) {
  formula <- as.formula(paste('w3FA_TFAP_resinv', "~", paste(predictors, collapse = " + ")))
  
  model <- lm(formula, data = subgroups[[i]], na.action = na.exclude)
  
  summary_model <- summary(model)

# Extract beta and standard errors of coefficients
  status_beta <- model$coefficients['Status']
  status_se <- summary_model$coefficients["Status", "Std. Error"]
  
  #Calculate 95% interval
  
  calculate_ci_lower(status_beta, status_se)
  calculate_ci_upper(status_beta, status_se)
  
  effect_df <- data.frame(
  Beta = status_beta,
  SE = status_se,
  rs35473591_CT = unique(subgroups[[i]]['rs35473591_CT'])
)
  final_df <- rbind(final_df, effect_df)
}

final_df$Lower = calculate_ci_lower(final_df$Beta, final_df$SE)
final_df$Upper = calculate_ci_upper(final_df$Beta, final_df$SE)


p <- ggplot(final_df, aes(x = factor(rs35473591_CT), y = Beta, colour = factor(rs35473591_CT))) +
  theme_linedraw() +
  geom_pointrange(aes(ymin = Lower, ymax = Upper)) +
  labs(x = NULL,y = NULL) +
  scale_colour_manual(values = c("0" = "darkorange", "1" = "indianred3", "2"= "#3399CC"),
                      labels = c("0" = "CT/CT", "1" = "C/CT", "2" = "CC")) +
  #scale_x_discrete(labels = c("0" = "CT/CT", "1" = "C/CT", "2" = "CC")) +
  scale_x_discrete(labels = NULL) +
  theme(axis.text = element_text(size = unit(8, "points"))) +
  theme(text = element_text(family = "Arial")) +
  theme(legend.position = "none")
  
  
print(p)

ggsave("genotype beta plot log.png", p, width = 3, height = 2, units = "in")

```
